version: "2"

services:
  hastnama-blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hastnama-blog
    entrypoint: sh entrypoint.sh
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node
